/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新規登録 + 同意取得 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignupRequest"];
                };
            };
            responses: {
                /** @description 登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["AuthResponse"];
                        };
                    };
                };
                /** @description メール重複 or 削除猶予中 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description バリデーション失敗 or 同意未取得 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description レート上限 */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** メールサインイン */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SigninRequest"];
                };
            };
            responses: {
                /** @description サインイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["AuthResponse"];
                        };
                    };
                };
                /** @description 認証情報不正 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description アカウントロック or 削除猶予中 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description レート上限 */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** サインアウト */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Magic Link 発行 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description メール送信受付 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description レート上限 */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google OAuth 連携 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Google にリダイレクト */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** GitHub OAuth 連携 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description GitHub にリダイレクト */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth callback */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description アプリにリダイレクト */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** パスワードリセット */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description リセットメール送信 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 現在のユーザー情報 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー情報 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 退会申請（30 日猶予開始） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 退会申請受付 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** Format: date-time */
                                deletion_scheduled_at?: string;
                                /** Format: date-time */
                                hard_delete_at?: string;
                                /** Format: date-time */
                                cancellation_deadline?: string;
                            };
                        };
                    };
                };
                /** @description 単一オーナーで他メンバー在籍 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/account/cancel-deletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退会キャンセル（30 日猶予中のみ） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description キャンセル成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 既に hard delete 済 or 猶予期間外 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 所属 WS 一覧 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WS 一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Workspace"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新規 WS 作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Workspace"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プロジェクト一覧（カーソル） */
        get: {
            parameters: {
                query?: {
                    workspace_id?: string;
                    status?: string;
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Project"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新規プロジェクト */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Project"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** プロジェクト KPI ダッシュボード */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ダッシュボード */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: Record<string, never>;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** タスク再生（dispatcher へ） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PlayTaskRequest"];
                };
            };
            responses: {
                /** @description 再生開始 or キュー投入 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["PlayTaskResponse"];
                        };
                    };
                };
                /** @description lifecycle 違反 or 依存未完 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Bridge オフライン or 並列上限 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kanban/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** kanban_complete (Hermes 互換) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["KanbanCompleteRequest"];
                };
            };
            responses: {
                /** @description タスク遷移完了 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** Format: uuid */
                                task_id?: string;
                                /** @enum {string} */
                                new_lifecycle_stage?: "done" | "awaiting" | "blocked" | "triage";
                                approval_required?: boolean;
                            };
                        };
                    };
                };
                /** @description Bridge token 不正 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 承認待ち一覧（5 種統合） */
        get: {
            parameters: {
                query?: {
                    category?: "task_approval" | "phase_approval" | "scope_change" | "knowledge_promotion" | "comment_response" | "all";
                    project_id?: string;
                    status?: "pending" | "all";
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ApprovalInboxEntry"][];
                            meta?: components["schemas"]["PaginationMeta"] & {
                                counts?: Record<string, never>;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-inbox/{id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 承認判断 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApprovalDecideRequest"];
                };
            };
            responses: {
                /** @description 判断適用 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 既に判断済 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** クライアントサインイン（別 JWT 系統） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientSigninRequest"];
                };
            };
            responses: {
                /** @description client_access_token 発行 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ClientSigninResponse"];
                        };
                    };
                };
                /** @description 招待トークン不正 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 招待期限切れ */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** クライアントプロジェクトビュー（限定 UI） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 限定情報 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description project_id 不一致 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "BAD_REQUEST" | "UNAUTHENTICATED" | "INVALID_CREDENTIALS" | "INVALID_BRIDGE_TOKEN" | "INVALID_INVITATION_TOKEN" | "FORBIDDEN" | "ACCOUNT_LOCKED" | "ACCOUNT_DELETED" | "NOT_FOUND" | "CONFLICT" | "INVALID_LIFECYCLE_STAGE" | "DEPENDENCIES_NOT_MET" | "ALREADY_DECIDED" | "EMAIL_ALREADY_REGISTERED" | "EMAIL_IN_DELETION_GRACE" | "OWNER_OF_WORKSPACE_WITH_OTHERS" | "INVITATION_EXPIRED" | "VALIDATION_ERROR" | "CONSENT_REQUIRED" | "RATE_LIMITED" | "BYOK_QUOTA_EXCEEDED" | "INTERNAL_ERROR" | "BRIDGE_OFFLINE" | "PARALLEL_LIMIT_REACHED" | "F_CTX01_TIMEOUT";
                message: string;
                details?: {
                    field?: string;
                    code?: string;
                    message?: string;
                }[];
                /** Format: uuid */
                request_id: string;
                trace_id?: string;
            };
        };
        PaginationMeta: {
            next_cursor?: string | null;
            limit?: number;
            total_estimate?: number;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            avatar_url?: string | null;
            /** @enum {string} */
            language: "ja" | "en";
            /** @default true */
            ai_learning_opt_out: boolean;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
            consents: {
                terms: boolean;
                privacy: boolean;
                cross_border: boolean;
                marketing?: boolean;
            };
        };
        SigninRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            workspace?: components["schemas"]["Workspace"];
            access_token: string;
            /** @description opaque, httpOnly cookie */
            refresh_token?: string;
        };
        Workspace: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string | null;
            member_count?: number;
            project_count?: number;
            /** @enum {string} */
            plan?: "free" | "pro" | "enterprise";
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        InviteMemberRequest: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "owner" | "member" | "viewer";
            message?: string;
        };
        Project: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            workspace_id?: string;
            name?: string;
            description?: string | null;
            /** @enum {string} */
            type?: "self_product" | "client_project" | "personal";
            /** @enum {string} */
            status?: "in_progress" | "draft" | "paused" | "archived";
            ai_learning_opt_out?: boolean;
            /** @enum {string} */
            current_phase?: "hearing" | "requirements" | "architecture" | "design" | "breakdown" | "tasks" | "implementation" | "verification" | "delivery";
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateProjectRequest: {
            /** Format: uuid */
            workspace_id: string;
            name: string;
            /** @enum {string} */
            type: "self_product" | "client_project" | "personal";
            description?: string;
        };
        Task: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            project_id?: string;
            phase?: string;
            category?: string;
            title?: string;
            description?: string | null;
            /** @enum {string} */
            type?: "foundation" | "screen" | "feature" | "verification" | "infrastructure" | "migration";
            estimated_hours?: number;
            /** @enum {string} */
            priority?: "critical" | "high" | "medium" | "low";
            /**
             * @description Hermes 6 列モデル
             * @enum {string}
             */
            lifecycle_stage?: "triage" | "ready" | "in_progress" | "blocked" | "awaiting" | "done";
            /** @enum {string|null} */
            dispatch_status?: "queued" | "spawning" | "running" | "completing" | "dead" | "reclaimed" | null;
            /** @enum {string} */
            assigned_employee_id?: "jarvis" | "tony" | "natasha" | "steve" | "peter" | "strange" | "wanda" | "thor" | "vision" | "tchalla";
            summary?: string | null;
            metadata?: Record<string, never>;
            blocked_reason?: string | null;
            retry_count?: number;
            worktree_path?: string | null;
            worker_pid?: number | null;
            dependencies?: string[];
            prerequisites?: string[];
            blocks?: string[];
            /** Format: uuid */
            acceptance_criteria_id?: string | null;
            /** Format: uuid */
            mock_id?: string | null;
            /** Format: uuid */
            parent_task_id?: string | null;
            /** @enum {string} */
            origin_type?: "initial_decomposition" | "refactor" | "scope_change_auto" | "manual_added";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        PlayTaskRequest: {
            /** @default false */
            force: boolean;
        };
        PlayTaskResponse: {
            /** Format: uuid */
            task_id?: string;
            lifecycle_stage?: string;
            dispatch_status?: string;
            /** Format: uuid */
            execution_id?: string;
            worktree_path?: string;
            bridge_command?: string;
            /** @description 並列上限超過時のキュー位置 */
            queue_position?: number;
        };
        KanbanCompleteRequest: {
            /** Format: uuid */
            task_id: string;
            summary: string;
            metadata: {
                score: number;
                ac_pass_rate: number;
                test_pass_rate: number;
                verification_score: number;
                files_changed?: string[];
                retry_count: number;
            };
        };
        ApprovalInboxEntry: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            category?: "task_approval" | "phase_approval" | "scope_change" | "knowledge_promotion" | "comment_response";
            urgent?: boolean;
            title?: string;
            preview?: string;
            source_ref?: {
                type?: string;
                /** Format: uuid */
                id?: string;
            };
            detected_by?: {
                employee_id?: string;
                /** Format: date-time */
                at?: string;
            };
            impact_analysis?: Record<string, never>;
            score?: number | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            decided_at?: string | null;
        };
        ApprovalDecideRequest: {
            /** @enum {string} */
            decision: "approve" | "reject" | "defer";
            reason?: string;
            scope_change_options?: {
                rerun_phases?: ("hearing" | "requirements" | "architecture" | "design" | "breakdown" | "tasks" | "implementation" | "verification" | "delivery")[];
            };
        };
        ClientSigninRequest: {
            invitation_token: string;
            display_name?: string;
        };
        ClientSigninResponse: {
            client_access_token?: string;
            project?: {
                /** Format: uuid */
                id?: string;
                name?: string;
            };
            /** Format: date-time */
            expires_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
