#!/usr/bin/env bash
# OpenAPI → TS / Pydantic 自動生成パイプライン
#
# Usage: ./scripts/sync-types.sh
#
# 動作:
#   1. 07_api_design/openapi.yaml → packages/api-types/src/openapi.ts  (openapi-typescript)
#   2. 07_api_design/openapi.yaml → apps/api/src/_generated/openapi_models.py  (datamodel-code-generator)
#
# CI (Gate #7) では本スクリプトを実行後 git diff で drift を検出する。
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OPENAPI="07_api_design/openapi.yaml"

if [ ! -f "$OPENAPI" ]; then
  echo "::error::$OPENAPI not found" >&2
  exit 1
fi

# 1) TS types (openapi-typescript)
TS_OUT="packages/api-types/src/openapi.ts"
mkdir -p "$(dirname "$TS_OUT")"
echo "→ generating $TS_OUT"
npx --yes openapi-typescript@7.4.4 "$OPENAPI" --output "$TS_OUT"

# 2) Pydantic models (datamodel-code-generator)
PY_OUT="apps/api/src/_generated/openapi_models.py"
mkdir -p "$(dirname "$PY_OUT")"
echo "→ generating $PY_OUT"
# uv tool で datamodel-code-generator を実行 (project deps を汚さない)
uv tool run --from 'datamodel-code-generator[http]' \
  datamodel-codegen \
  --input "$OPENAPI" \
  --input-file-type openapi \
  --output "$PY_OUT" \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.12 \
  --use-double-quotes \
  --use-schema-description \
  --use-field-description \
  --reuse-model \
  --use-annotated \
  --disable-timestamp

# 3) generated marker (apps/api/src/_generated/__init__.py を維持)
if [ ! -f apps/api/src/_generated/__init__.py ]; then
  cat > apps/api/src/_generated/__init__.py <<'PYINIT'
"""Generated by scripts/sync-types.sh from 07_api_design/openapi.yaml.

DO NOT EDIT MANUALLY. Re-run scripts/sync-types.sh to update.
"""
PYINIT
fi

echo "✓ sync-types complete"
