# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, EmailStr, Field


class Code(StrEnum):
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_BRIDGE_TOKEN = "INVALID_BRIDGE_TOKEN"
    INVALID_INVITATION_TOKEN = "INVALID_INVITATION_TOKEN"
    FORBIDDEN = "FORBIDDEN"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_DELETED = "ACCOUNT_DELETED"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    INVALID_LIFECYCLE_STAGE = "INVALID_LIFECYCLE_STAGE"
    DEPENDENCIES_NOT_MET = "DEPENDENCIES_NOT_MET"
    ALREADY_DECIDED = "ALREADY_DECIDED"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    EMAIL_IN_DELETION_GRACE = "EMAIL_IN_DELETION_GRACE"
    OWNER_OF_WORKSPACE_WITH_OTHERS = "OWNER_OF_WORKSPACE_WITH_OTHERS"
    INVITATION_EXPIRED = "INVITATION_EXPIRED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    CONSENT_REQUIRED = "CONSENT_REQUIRED"
    RATE_LIMITED = "RATE_LIMITED"
    BYOK_QUOTA_EXCEEDED = "BYOK_QUOTA_EXCEEDED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    BRIDGE_OFFLINE = "BRIDGE_OFFLINE"
    PARALLEL_LIMIT_REACHED = "PARALLEL_LIMIT_REACHED"
    F_CTX01_TIMEOUT = "F_CTX01_TIMEOUT"


class Detail(BaseModel):
    field: str | None = None
    code: str | None = None
    message: str | None = None


class Error1(BaseModel):
    code: Code
    message: str
    details: list[Detail] | None = None
    request_id: UUID
    trace_id: str | None = None


class Error(BaseModel):
    error: Error1


class PaginationMeta(BaseModel):
    next_cursor: str | None = None
    limit: int | None = None
    total_estimate: int | None = None


class Language(StrEnum):
    ja = "ja"
    en = "en"


class User(BaseModel):
    id: UUID
    email: EmailStr
    display_name: Annotated[str, Field(max_length=50)]
    avatar_url: str | None = None
    language: Language
    ai_learning_opt_out: bool
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class Consents(BaseModel):
    terms: bool
    privacy: bool
    cross_border: bool
    marketing: bool | None = None


class SignupRequest(BaseModel):
    email: Annotated[EmailStr, Field(max_length=254)]
    password: Annotated[str, Field(max_length=128, min_length=8)]
    display_name: Annotated[str, Field(max_length=50)]
    consents: Consents


class SigninRequest(BaseModel):
    email: EmailStr
    password: str


class Plan(StrEnum):
    free = "free"
    pro = "pro"
    enterprise = "enterprise"


class Workspace(BaseModel):
    id: UUID | None = None
    name: str | None = None
    description: str | None = None
    member_count: int | None = None
    project_count: int | None = None
    plan: Plan | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Role(StrEnum):
    owner = "owner"
    member = "member"
    viewer = "viewer"


class InviteMemberRequest(BaseModel):
    email: EmailStr
    role: Role
    message: Annotated[str | None, Field(max_length=500)] = None


class Type(StrEnum):
    self_product = "self_product"
    client_project = "client_project"
    personal = "personal"


class Status(StrEnum):
    in_progress = "in_progress"
    draft = "draft"
    paused = "paused"
    archived = "archived"


class CurrentPhase(StrEnum):
    hearing = "hearing"
    requirements = "requirements"
    architecture = "architecture"
    design = "design"
    breakdown = "breakdown"
    tasks = "tasks"
    implementation = "implementation"
    verification = "verification"
    delivery = "delivery"


class Project(BaseModel):
    id: UUID | None = None
    workspace_id: UUID | None = None
    name: str | None = None
    description: str | None = None
    type: Type | None = None
    status: Status | None = None
    ai_learning_opt_out: bool | None = None
    current_phase: CurrentPhase | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class CreateProjectRequest(BaseModel):
    workspace_id: UUID
    name: Annotated[str, Field(max_length=100)]
    type: Type
    description: str | None = None


class Type2(StrEnum):
    foundation = "foundation"
    screen = "screen"
    feature = "feature"
    verification = "verification"
    infrastructure = "infrastructure"
    migration = "migration"


class Priority(StrEnum):
    critical = "critical"
    high = "high"
    medium = "medium"
    low = "low"


class LifecycleStage(StrEnum):
    """
    Hermes 6 列モデル
    """

    triage = "triage"
    ready = "ready"
    in_progress = "in_progress"
    blocked = "blocked"
    awaiting = "awaiting"
    done = "done"


class DispatchStatus(StrEnum):
    queued = "queued"
    spawning = "spawning"
    running = "running"
    completing = "completing"
    dead = "dead"
    reclaimed = "reclaimed"


class AssignedEmployeeId(StrEnum):
    jarvis = "jarvis"
    tony = "tony"
    natasha = "natasha"
    steve = "steve"
    peter = "peter"
    strange = "strange"
    wanda = "wanda"
    thor = "thor"
    vision = "vision"
    tchalla = "tchalla"


class OriginType(StrEnum):
    initial_decomposition = "initial_decomposition"
    refactor = "refactor"
    scope_change_auto = "scope_change_auto"
    manual_added = "manual_added"


class Task(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    phase: str | None = None
    category: str | None = None
    title: str | None = None
    description: str | None = None
    type: Type2 | None = None
    estimated_hours: Annotated[int | None, Field(ge=1, le=24)] = None
    priority: Priority | None = None
    lifecycle_stage: LifecycleStage | None = None
    """
    Hermes 6 列モデル
    """
    dispatch_status: DispatchStatus | None = None
    assigned_employee_id: AssignedEmployeeId | None = None
    summary: str | None = None
    metadata: dict[str, Any] | None = None
    blocked_reason: str | None = None
    retry_count: Annotated[int | None, Field(ge=0, le=3)] = None
    worktree_path: str | None = None
    worker_pid: int | None = None
    dependencies: list[UUID] | None = None
    prerequisites: list[UUID] | None = None
    blocks: list[UUID] | None = None
    acceptance_criteria_id: UUID | None = None
    mock_id: UUID | None = None
    parent_task_id: UUID | None = None
    origin_type: OriginType | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class PlayTaskRequest(BaseModel):
    force: bool | None = False


class PlayTaskResponse(BaseModel):
    task_id: UUID | None = None
    lifecycle_stage: str | None = None
    dispatch_status: str | None = None
    execution_id: UUID | None = None
    worktree_path: str | None = None
    bridge_command: str | None = None
    queue_position: int | None = None
    """
    並列上限超過時のキュー位置
    """


class Metadata(BaseModel):
    score: Annotated[float, Field(ge=0.0, le=1.0)]
    ac_pass_rate: float
    test_pass_rate: float
    verification_score: float
    files_changed: list[str] | None = None
    retry_count: int


class KanbanCompleteRequest(BaseModel):
    task_id: UUID
    summary: str
    metadata: Metadata


class Category(StrEnum):
    task_approval = "task_approval"
    phase_approval = "phase_approval"
    scope_change = "scope_change"
    knowledge_promotion = "knowledge_promotion"
    comment_response = "comment_response"


class SourceRef(BaseModel):
    type: str | None = None
    id: UUID | None = None


class DetectedBy(BaseModel):
    employee_id: str | None = None
    at: AwareDatetime | None = None


class ApprovalInboxEntry(BaseModel):
    id: UUID | None = None
    category: Category | None = None
    urgent: bool | None = None
    title: str | None = None
    preview: str | None = None
    source_ref: SourceRef | None = None
    detected_by: DetectedBy | None = None
    impact_analysis: dict[str, Any] | None = None
    score: float | None = None
    created_at: AwareDatetime | None = None
    decided_at: AwareDatetime | None = None


class Decision(StrEnum):
    approve = "approve"
    reject = "reject"
    defer = "defer"


class ScopeChangeOptions(BaseModel):
    rerun_phases: list[CurrentPhase] | None = None


class ApprovalDecideRequest(BaseModel):
    decision: Decision
    reason: str | None = None
    scope_change_options: ScopeChangeOptions | None = None


class ClientSigninRequest(BaseModel):
    invitation_token: str
    display_name: str | None = None


class Project1(BaseModel):
    id: UUID | None = None
    name: str | None = None


class ClientSigninResponse(BaseModel):
    client_access_token: str | None = None
    project: Project1 | None = None
    expires_at: AwareDatetime | None = None


class AuthResponse(BaseModel):
    user: User
    workspace: Workspace | None = None
    access_token: str
    refresh_token: str | None = None
    """
    opaque, httpOnly cookie
    """
