# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, RootModel


class Code(StrEnum):
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_BRIDGE_TOKEN = "INVALID_BRIDGE_TOKEN"
    INVALID_INVITATION_TOKEN = "INVALID_INVITATION_TOKEN"
    FORBIDDEN = "FORBIDDEN"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_DELETED = "ACCOUNT_DELETED"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    INVALID_LIFECYCLE_STAGE = "INVALID_LIFECYCLE_STAGE"
    DEPENDENCIES_NOT_MET = "DEPENDENCIES_NOT_MET"
    ALREADY_DECIDED = "ALREADY_DECIDED"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    EMAIL_IN_DELETION_GRACE = "EMAIL_IN_DELETION_GRACE"
    OWNER_OF_WORKSPACE_WITH_OTHERS = "OWNER_OF_WORKSPACE_WITH_OTHERS"
    INVITATION_EXPIRED = "INVITATION_EXPIRED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    CONSENT_REQUIRED = "CONSENT_REQUIRED"
    RATE_LIMITED = "RATE_LIMITED"
    BYOK_QUOTA_EXCEEDED = "BYOK_QUOTA_EXCEEDED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    BRIDGE_OFFLINE = "BRIDGE_OFFLINE"
    PARALLEL_LIMIT_REACHED = "PARALLEL_LIMIT_REACHED"
    F_CTX01_TIMEOUT = "F_CTX01_TIMEOUT"


class Detail(BaseModel):
    field: str | None = None
    code: str | None = None
    message: str | None = None


class Error1(BaseModel):
    code: Code
    message: str
    details: list[Detail] | None = None
    request_id: UUID
    trace_id: str | None = None


class Error(BaseModel):
    error: Error1


class PaginationMeta(BaseModel):
    next_cursor: str | None = None
    limit: int | None = None
    total_estimate: int | None = None


class Language(StrEnum):
    ja = "ja"
    en = "en"


class User(BaseModel):
    id: UUID
    email: EmailStr
    display_name: Annotated[str, Field(max_length=50)]
    avatar_url: str | None = None
    language: Language
    ai_learning_opt_out: bool
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class Me(BaseModel):
    id: UUID
    email: EmailStr
    display_name: str


class MeUpdate(BaseModel):
    display_name: Annotated[str, Field(max_length=100, min_length=1)]


class Kind(StrEnum):
    project = "project"
    task = "task"
    knowledge = "knowledge"
    employee = "employee"


class SearchHit(BaseModel):
    id: str
    kind: Kind
    title: str
    snippet: str


class SigninRequest(BaseModel):
    email: EmailStr
    password: str


class TokenType(StrEnum):
    bearer = "bearer"


class SigninResponse(BaseModel):
    access_token: str
    """
    HS256 JWT (sub=user.id)
    """
    token_type: TokenType
    expires_at: AwareDatetime
    user_id: UUID
    email: EmailStr
    display_name: str | None = None
    refresh_token: str | None = None
    """
    opaque refresh token (T-A-04)
    """


class MagicLinkRequest(BaseModel):
    email: EmailStr
    redirect_url: Annotated[str | None, Field(max_length=500)] = None


class Delivery(StrEnum):
    email = "email"


class MagicLinkAccepted(BaseModel):
    accepted: bool
    delivery: Delivery


class MagicLinkVerifyRequest(BaseModel):
    email: EmailStr
    token: Annotated[str, Field(max_length=200, min_length=10)]


class Provider(StrEnum):
    google = "google"
    github = "github"


class OAuthRedirectResponse(BaseModel):
    authorize_url: str
    state: str
    provider: Provider


class PasswordResetRequest(BaseModel):
    email: EmailStr


class PasswordResetAccepted(BaseModel):
    accepted: bool


class PasswordResetConfirmRequest(BaseModel):
    email: EmailStr
    token: Annotated[str, Field(max_length=200, min_length=10)]
    new_password: Annotated[str, Field(max_length=128, min_length=8)]


class PasswordResetConfirmResponse(BaseModel):
    user_id: UUID
    email: EmailStr
    password_changed_at: AwareDatetime


class RefreshRequest(BaseModel):
    refresh_token: Annotated[str, Field(max_length=200, min_length=10)]


class RefreshResponse(BaseModel):
    access_token: str
    token_type: TokenType
    expires_at: AwareDatetime
    refresh_token: str
    """
    rotated new opaque token
    """


class AccountDeleteRequest(BaseModel):
    password: Annotated[str, Field(max_length=128, min_length=1)]
    reason: Annotated[str | None, Field(max_length=2000)] = None


class AccountDeleteResponse(BaseModel):
    user_id: UUID
    scheduled_purge_at: AwareDatetime
    deleted_at: AwareDatetime


class AccountRestoreRequest(BaseModel):
    email: EmailStr
    password: Annotated[str, Field(max_length=128, min_length=1)]


class AccountRestoreResponse(BaseModel):
    user_id: UUID
    restored_at: AwareDatetime


class FreezeRequest(BaseModel):
    note: str | None = None


class FreezeStatus(BaseModel):
    frozen: bool
    frozen_at: AwareDatetime | None = None
    frozen_by_user_id: UUID | None = None
    last_note: str | None = None
    total_paths: Annotated[int, Field(ge=0)]
    total_methods: Annotated[int, Field(ge=0)]
    evaluated_at: AwareDatetime


class ScreenCoverageEntry(BaseModel):
    screen_id: str
    endpoint_count: Annotated[int, Field(ge=0)]
    endpoints: list[str]


class ScreenCoverageReport(BaseModel):
    total_screens: Annotated[int, Field(ge=0)]
    covered_screens: Annotated[int, Field(ge=0)]
    uncovered_screens: list[str]
    coverage_pct: Annotated[float, Field(ge=0.0, le=100.0)]
    entries: list[ScreenCoverageEntry]
    evaluated_at: AwareDatetime


class Plan(StrEnum):
    free = "free"
    pro = "pro"
    enterprise = "enterprise"


class Workspace(BaseModel):
    id: UUID | None = None
    name: str | None = None
    description: str | None = None
    icon: str | None = None
    """
    絵文字または 1〜3 文字 (最大 8 バイト)。null は頭文字表示 (GAP-021)
    """
    member_count: int | None = None
    project_count: int | None = None
    plan: Plan | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Role(StrEnum):
    owner = "owner"
    member = "member"
    viewer = "viewer"


class InviteMemberRequest(BaseModel):
    email: EmailStr
    role: Role
    message: Annotated[str | None, Field(max_length=500)] = None


class Type(StrEnum):
    self_product = "self_product"
    client_project = "client_project"
    personal = "personal"


class Status(StrEnum):
    in_progress = "in_progress"
    draft = "draft"
    paused = "paused"
    archived = "archived"


class CurrentPhase(StrEnum):
    hearing = "hearing"
    requirements = "requirements"
    architecture = "architecture"
    design = "design"
    breakdown = "breakdown"
    tasks = "tasks"
    implementation = "implementation"
    verification = "verification"
    delivery = "delivery"


class Project(BaseModel):
    id: UUID | None = None
    workspace_id: UUID | None = None
    name: str | None = None
    client_name: Annotated[str | None, Field(max_length=200)] = None
    description: str | None = None
    type: Type | None = None
    status: Status | None = None
    ai_learning_opt_out: bool | None = None
    cross_project_knowledge: bool | None = None
    current_phase: CurrentPhase | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Kind1(StrEnum):
    api_key = "api_key"
    password = "password"
    token = "token"
    connection_string = "connection_string"
    other = "other"


class ProjectCredential(BaseModel):
    """
    プロジェクト・シークレットの1件（plaintext / encrypted は含まない、値マスク）
    """

    id: UUID
    project_id: UUID
    name: str
    kind: Kind1
    last4: str | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class CredentialCreate(BaseModel):
    name: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Kind1 | None = None
    value: Annotated[str, Field(max_length=10000, min_length=1)]
    """
    plaintext（保存時に暗号化）
    """


class CredentialUpdate(BaseModel):
    name: Annotated[str | None, Field(max_length=200, min_length=1)] = None
    kind: Kind1 | None = None


class CredentialRevealRequest(BaseModel):
    """
    GAP-131: reveal の再認証。TTL (既定 300 秒) 内の再認証が残っていれば省略可
    """

    password: Annotated[str | None, Field(max_length=200)] = None
    """
    ログインパスワードの再入力
    """


class CredentialReveal(BaseModel):
    """
    reveal 応答（権限者のみ・監査記録済の上で plaintext を返す）
    """

    id: UUID
    name: str
    value: str
    """
    plaintext（復号済）
    """


class CreateProjectRequest(BaseModel):
    workspace_id: UUID
    name: Annotated[str, Field(max_length=100)]
    type: Type
    description: str | None = None


class Type2(StrEnum):
    foundation = "foundation"
    screen = "screen"
    feature = "feature"
    verification = "verification"
    infrastructure = "infrastructure"
    migration = "migration"


class Priority(StrEnum):
    critical = "critical"
    high = "high"
    medium = "medium"
    low = "low"


class LifecycleStage(StrEnum):
    """
    Hermes 6 列モデル
    """

    triage = "triage"
    ready = "ready"
    in_progress = "in_progress"
    blocked = "blocked"
    awaiting = "awaiting"
    done = "done"


class DispatchStatus(StrEnum):
    queued = "queued"
    spawning = "spawning"
    running = "running"
    completing = "completing"
    dead = "dead"
    reclaimed = "reclaimed"


class AssignedEmployeeId(StrEnum):
    jarvis = "jarvis"
    tony = "tony"
    natasha = "natasha"
    steve = "steve"
    peter = "peter"
    strange = "strange"
    wanda = "wanda"
    thor = "thor"
    vision = "vision"
    tchalla = "tchalla"


class OriginType(StrEnum):
    initial_decomposition = "initial_decomposition"
    refactor = "refactor"
    scope_change_auto = "scope_change_auto"
    manual_added = "manual_added"


class Task(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    phase: str | None = None
    delivery_phase_id: UUID | None = None
    category: str | None = None
    title: str | None = None
    description: str | None = None
    type: Type2 | None = None
    estimated_hours: Annotated[int | None, Field(ge=1, le=24)] = None
    priority: Priority | None = None
    lifecycle_stage: LifecycleStage | None = None
    """
    Hermes 6 列モデル
    """
    dispatch_status: DispatchStatus | None = None
    assigned_employee_id: AssignedEmployeeId | None = None
    summary: str | None = None
    metadata: dict[str, Any] | None = None
    blocked_reason: str | None = None
    retry_count: Annotated[int | None, Field(ge=0, le=3)] = None
    worktree_path: str | None = None
    worker_pid: int | None = None
    dependencies: list[UUID] | None = None
    prerequisites: list[UUID] | None = None
    blocks: list[UUID] | None = None
    acceptance_criteria_id: UUID | None = None
    mock_id: UUID | None = None
    verifier_employee_id: UUID | None = None
    files_changed: list[str] | None = None
    mock_screen_name: str | None = None
    parent_task_id: UUID | None = None
    origin_type: OriginType | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class AcceptanceCriteria(BaseModel):
    id: UUID | None = None
    task_id: UUID | None = None
    html_path: str | None = None
    items: list[dict[str, Any]] | None = None
    version: int | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class TaskExecution(BaseModel):
    id: UUID | None = None
    task_id: UUID | None = None
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None
    duration_seconds: float | None = None
    """
    GAP-025④: 実測経過秒 (running は now 起点)
    """
    score: float | None = None
    ac_pass_rate: float | None = None
    test_pass_rate: float | None = None
    verification_score: float | None = None
    retry_count: int | None = None
    status: str | None = None
    claude_code_session_id: str | None = None
    logs_storage_path: str | None = None
    error_summary: str | None = None
    created_at: AwareDatetime | None = None


class Status1(StrEnum):
    active = "active"
    frozen = "frozen"


class DeliveryPhase(BaseModel):
    """
    GAP-152 — 納品単位のフェーズ (フェーズ1..N)。frozen = 確定済み (成果物凍結)。
    """

    id: UUID | None = None
    project_id: UUID | None = None
    seq: Annotated[int | None, Field(ge=1)] = None
    name: str | None = None
    status: Status1 | None = None
    note: str | None = None
    frozen_at: AwareDatetime | None = None
    mock_count: int | None = None
    output_count: int | None = None
    task_count: int | None = None
    stages_done: int | None = None
    stages_total: int | None = None


class Status2(StrEnum):
    pending = "pending"
    done = "done"
    skipped = "skipped"


class FlowStage(BaseModel):
    """
    GAP-150 — プロジェクト進行フローの 1 ステージ (現在ステージは最小 seq の pending)
    """

    id: UUID
    stage_key: str
    seq: int
    title: str
    department: str
    status: Status2
    skippable: bool
    hard_gate: bool
    """
    致命工程 — 完了に confirm=true 必須・スキップ不可
    """
    skip_reason: str | None = None
    completed_at: AwareDatetime | None = None
    current: bool
    employee_id: UUID | None = None
    employee_name: str | None = None
    employee_icon: str | None = None
    thread_id: UUID | None = None


class Mock(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    screen_name: str | None = None
    html_storage_path: str | None = None
    version: int | None = None
    parent_mock_id: UUID | None = None
    delivery_phase_id: UUID | None = None
    meta_tags: dict[str, Any] | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Kind4(StrEnum):
    """
    表示方法の決定に使う中身の種別。html=iframe / pdf=PDF ビューア / image=<img> / sheet=表 (プレビュー枠は出さない) / binary=DL のみ
    """

    html = "html"
    pdf = "pdf"
    image = "image"
    sheet = "sheet"
    binary = "binary"


class ContentUrl(BaseModel):
    url: str
    kind: Kind4 | None = None
    """
    表示方法の決定に使う中身の種別。html=iframe / pdf=PDF ビューア / image=<img> / sheet=表 (プレビュー枠は出さない) / binary=DL のみ
    """
    file_name: str | None = None
    """
    元のファイル名 (バイナリ成果物のみ)
    """
    mime: str | None = None


class Role1(StrEnum):
    coo = "coo"
    lead = "lead"
    member = "member"


class Department(StrEnum):
    executive = "executive"
    sales = "sales"
    product = "product"
    architecture = "architecture"
    design = "design"
    dev_qa = "dev_qa"
    cross_functional = "cross_functional"


class TonePreset(StrEnum):
    polite = "polite"
    friendly = "friendly"
    casual = "casual"
    concise = "concise"
    coaching = "coaching"


class AiEmployee(BaseModel):
    id: UUID | None = None
    workspace_id: UUID | None = None
    template_id: UUID | None = None
    name: str | None = None
    display_name: str | None = None
    icon: str | None = None
    role: Role1 | None = None
    department: Department | None = None
    tone_preset: TonePreset | None = None
    custom_tone_text: str | None = None
    attached_skills: list[UUID] | None = None
    attached_knowledge_cats: list[str] | None = None
    is_default: bool | None = None
    archived: bool | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class EmployeeIconUploadUrlRequest(BaseModel):
    file_name: Annotated[str, Field(max_length=200, min_length=1)]
    mime_type: str
    """
    image/png | image/jpeg | image/webp のみ許可
    """
    file_size_bytes: Annotated[int, Field(ge=1)]
    """
    512KB (524288) 以下
    """


class EmployeeIconUploadUrlResponse(BaseModel):
    upload_url: str
    """
    実ファイル PUT 先の署名付き URL
    """
    storage_path: str
    """
    PUT 完了後に PATCH icon へ格納する path (avatars/...)
    """


class AiEmployeeTemplate(BaseModel):
    id: UUID | None = None
    default_name: str | None = None
    default_display_name: str | None = None
    default_icon: str | None = None
    department: Department | None = None
    role: Role1 | None = None
    default_skills: list[UUID] | None = None
    default_knowledge_cats: list[str] | None = None
    system_prompt: str | None = None
    specialty: str | None = None
    version: int | None = None
    is_active: bool | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class ActorType(StrEnum):
    ai = "ai"
    user = "user"
    system = "system"
    anonymous = "anonymous"


class AuditLog(BaseModel):
    id: UUID | None = None
    workspace_id: UUID | None = None
    actor_type: ActorType | None = None
    actor_id: str | None = None
    action: str | None = None
    target_type: str | None = None
    target_id: UUID | None = None
    before: dict[str, Any] | None = None
    after: dict[str, Any] | None = None
    ip_address: str | None = None
    created_at: AwareDatetime | None = None


class AdminSkill(BaseModel):
    """
    運営 admin 向け skill 詳細 (T-A-42)。
    """

    id: UUID | None = None
    name: str | None = None
    version: str | None = None
    description: str | None = None
    content_md: str | None = None
    assets_storage_path: str | None = None
    allowed_employee_roles: list[str] | None = None
    allowed_employee_ids: list[UUID] | None = None
    is_active: bool | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class SkillLite(BaseModel):
    """
    認証ユーザー向けスキルカタログ (S-C01/S-C02 表示用 read-only。RLS skills_select_all)。
    """

    id: UUID | None = None
    name: str | None = None
    version: str | None = None
    description: str | None = None
    is_active: bool | None = None


class SkillCreate(BaseModel):
    """
    スキル新規登録（SKILL.md upload, T-A-49 / F-007）。name+version unique・version semver。
    """

    name: Annotated[str, Field(max_length=200, min_length=1)]
    version: Annotated[str, Field(max_length=64, min_length=1)]
    """
    semver (例 1.0.0)
    """
    content_md: Annotated[str, Field(min_length=1)]
    description: str | None = None
    assets_storage_path: str | None = None
    allowed_employee_roles: Annotated[list[str] | None, Field(max_length=50)] = None
    allowed_employee_ids: Annotated[list[UUID] | None, Field(max_length=200)] = None
    is_active: bool | None = True


class SkillUpdate(BaseModel):
    """
    スキル編集（name/version は不変。新バージョンは create で別行, T-A-49）。
    """

    content_md: Annotated[str | None, Field(min_length=1)] = None
    description: str | None = None
    assets_storage_path: str | None = None
    allowed_employee_roles: Annotated[list[str] | None, Field(max_length=50)] = None
    allowed_employee_ids: Annotated[list[UUID] | None, Field(max_length=200)] = None
    is_active: bool | None = None


class SkillAttachRequest(BaseModel):
    """
    AI 社員へのスキル装着 / 解除（T-A-49）。
    """

    ai_employee_id: UUID
    attached: bool | None = True
    """
    true=装着 / false=解除
    """


class AdminTemplate(BaseModel):
    """
    運営 admin 向け AI 社員テンプレ詳細 (T-A-42)。
    """

    id: UUID | None = None
    default_name: str | None = None
    default_display_name: str | None = None
    default_icon: str | None = None
    department: str | None = None
    role: str | None = None
    default_skills: list[UUID] | None = None
    default_knowledge_cats: list[str] | None = None
    system_prompt: str | None = None
    specialty: str | None = None
    version: int | None = None
    is_active: bool | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class DefaultKnowledgeCat(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1)]


class AdminTemplateUpdate(BaseModel):
    """
    AI 社員テンプレの部分更新 (GAP-031⑤ / T-A-42 scope expand)。未指定フィールドは変更しない。
    """

    default_display_name: Annotated[str | None, Field(max_length=100, min_length=1)] = (
        None
    )
    department: Department | None = None
    role: Role1 | None = None
    system_prompt: Annotated[str | None, Field(max_length=20000, min_length=1)] = None
    specialty: Annotated[str | None, Field(max_length=500)] = None
    default_skills: Annotated[list[UUID] | None, Field(max_length=50)] = None
    default_knowledge_cats: Annotated[
        list[DefaultKnowledgeCat] | None, Field(max_length=50)
    ] = None


class AdminTemplateDeployment(BaseModel):
    """
    テンプレの実展開先 (ai_employees.template_id 参照の実カウント — GAP-031⑤)。
    """

    template_id: UUID | None = None
    workspace_count: int | None = None
    employee_count: int | None = None


class AdminDashboard(BaseModel):
    """
    運営 admin dashboard 集計 (T-A-41 / admin 所属 workspaces scope)。
    """

    workspace_count: int | None = None
    project_count: int | None = None
    ai_employee_count: int | None = None
    audit_log_count_24h: int | None = None
    generated_at: AwareDatetime | None = None


class AdminGoal(BaseModel):
    """
    事業 KPI 目標の記録 (E admin_goals — GAP-019。運営が明示的に設定)
    """

    id: UUID | None = None
    goal_key: str | None = None
    title: str | None = None
    target_count: int | None = None
    deadline: date | None = None
    note: str | None = None
    updated_at: AwareDatetime | None = None


class AdminMission(BaseModel):
    """
    ミッションヒーロー実データ (GAP-019 — current/added_30d は実カウント)
    """

    goal: AdminGoal | None = None
    current_count: int | None = None
    added_30d: int | None = None
    remaining: int | None = None
    months_left: int | None = None
    needed_per_month: int | None = None


class Point(BaseModel):
    week_start: date | None = None
    workspaces: int | None = None
    projects: int | None = None


class AdminTrends(BaseModel):
    """
    週次トレンド実累計 (GAP-019。billing 未導入のため MRR は実額 0)
    """

    points: list[Point] | None = None
    billing_enabled: bool | None = None
    mrr_yen: int | None = None


class Channel(StrEnum):
    referral = "referral"
    sns = "sns"
    personal = "personal"
    other = "other"


class AcquisitionRecord(BaseModel):
    """
    取得チャネルの記録 1 件 (E acquisition_records — GAP-019)
    """

    id: UUID | None = None
    channel: Channel | None = None
    note: str | None = None
    occurred_on: date | None = None
    created_at: AwareDatetime | None = None


class Channel1(BaseModel):
    channel: str | None = None
    count: int | None = None


class Acquisitions(BaseModel):
    channels: list[Channel1] | None = None
    recent: list[AcquisitionRecord] | None = None
    total: int | None = None


class Source(StrEnum):
    api = "api"
    web = "web"
    worker = "worker"


class Level(StrEnum):
    error = "error"
    warning = "warning"


class ErrorLogEntry(BaseModel):
    id: UUID
    occurred_at: AwareDatetime
    source: Source
    level: Level
    kind: str
    """
    例外クラス名 / エラー種別
    """
    message: str
    """
    秘匿値はマスク済み
    """
    path: str | None = None
    method: str | None = None
    status_code: int | None = None
    fingerprint: str
    """
    同種エラーをまとめる key
    """
    count_24h: int
    """
    同じ fingerprint の直近 24h 件数
    """


class Status3(StrEnum):
    ok = "ok"
    warn = "warn"
    err = "err"


class HealthCheckRow(BaseModel):
    """
    プラットフォーム健全性 1 行 (GAP-019 — 実計測/実設定状態のみ)
    """

    name: str | None = None
    status: Status3 | None = None
    detail: str | None = None
    meta: str | None = None


class Category(StrEnum):
    bug = "bug"
    feature = "feature"
    praise = "praise"
    other = "other"


class Status4(StrEnum):
    open = "open"
    resolved = "resolved"


class BetaFeedback(BaseModel):
    """
    ベータ FB (E beta_feedback — GAP-019)
    """

    id: UUID | None = None
    email: str | None = None
    category: Category | None = None
    content: str | None = None
    status: Status4 | None = None
    created_at: AwareDatetime | None = None
    resolved_at: AwareDatetime | None = None


class AdminCost(BaseModel):
    """
    運営コスト記録 1 件 (E admin_costs — GAP-019)
    """

    id: UUID | None = None
    month: date | None = None
    name: str | None = None
    description: str | None = None
    amount_yen: int | None = None


class AdminCosts(BaseModel):
    month: date | None = None
    items: list[AdminCost] | None = None
    total_yen: int | None = None


class AdminPlatformStats(BaseModel):
    """
    platform 横断統計 (GAP-019 — KPI bento 拡張の実データ)
    """

    task_executions_30d: int | None = None
    avg_score_30d: float | None = None
    beta_feedback_total: int | None = None
    beta_feedback_open: int | None = None
    bridge_connected: int | None = None
    users_total: int | None = None
    users_deleted_30d: int | None = None
    workspaces_added_30d: int | None = None


class AdminUser(BaseModel):
    """
    運営 admin 用メンバー詳細 (T-A-41 / workspace_member_details definer 経由)。
    """

    user_id: UUID | None = None
    email: str | None = None
    display_name: str | None = None
    role: str | None = None
    joined_at: AwareDatetime | None = None
    workspace_id: UUID | None = None


class ClientInvitation(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    email: EmailStr | None = None
    scopes: list[str] | None = None
    expires_at: AwareDatetime | None = None
    used_at: AwareDatetime | None = None
    revoked_at: AwareDatetime | None = None
    client_display_name: str | None = None
    use_count: Annotated[int | None, Field(ge=0)] = None
    """
    ポータルサインイン成功回数 (GAP-027②)
    """
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class ClientInvitationWithToken(ClientInvitation):
    token: str | None = None
    """
    生成時のみ返る raw token (招待 URL 用)
    """


class WorkspaceMember(BaseModel):
    workspace_id: UUID | None = None
    user_id: UUID | None = None
    email: EmailStr | None = None
    display_name: str | None = None
    role: Role | None = None
    joined_at: AwareDatetime | None = None


class ChatThread(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    ai_employee_id: UUID | None = None
    title: str | None = None
    archived: bool | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    message_count: int | None = 0
    """
    一覧表示用のメッセージ件数 (S-F01/S-E01)
    """
    phase_id: UUID | None = None
    """
    スレッドの属する工程。null=工程横断 (S-E01 グルーピング)
    """
    last_message_preview: str | None = None
    """
    一覧の最終メッセージ抜粋 (S-E01 スレッドカード)
    """


class ChatAttachment(BaseModel):
    file_name: Annotated[str, Field(max_length=200, min_length=1)]
    mime_type: str
    """
    png/jpeg/webp/gif/pdf/plain/markdown/csv/zip のみ許可
    """
    file_size_bytes: Annotated[int, Field(ge=1)]
    """
    10MB (10485760) 以下
    """
    storage_path: str
    """
    chat-attachments/{thread_id}/... (他スレッド配下は 422)
    """


class ChatAttachmentUploadUrlRequest(BaseModel):
    thread_id: UUID
    file_name: Annotated[str, Field(max_length=200, min_length=1)]
    mime_type: str
    file_size_bytes: Annotated[int, Field(ge=1)]


class ChatAttachmentUploadUrlResponse(BaseModel):
    upload_url: str
    """
    実ファイル PUT 先の署名付き URL
    """
    storage_path: str
    """
    送信時の attachments に含める path
    """


class Command(StrEnum):
    """
    decision = /決定 (確定事項記録) / task = /タスク化 (triage 起票)。/要約 は LLM 依頼のため SSE 経路
    """

    decision = "decision"
    task = "task"


class ChatCommandRequest(BaseModel):
    command: Command
    """
    decision = /決定 (確定事項記録) / task = /タスク化 (triage 起票)。/要約 は LLM 依頼のため SSE 経路
    """
    args: Annotated[str, Field(max_length=2000, min_length=1)]


class Command1(StrEnum):
    decision = "decision"
    task = "task"


class ChatCommandResponse(BaseModel):
    command: Command1
    target_type: str
    target_id: UUID
    system_message_id: UUID
    note: str


class Role5(StrEnum):
    user = "user"
    assistant = "assistant"
    system = "system"
    tool = "tool"


class ChatMessage(BaseModel):
    id: UUID | None = None
    thread_id: UUID | None = None
    role: Role5 | None = None
    content: str | None = None
    parent_message_id: UUID | None = None
    token_count: int | None = None
    attachments: list[ChatAttachment] | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Value(StrEnum):
    up = "up"
    down = "down"


class MessageFeedback(BaseModel):
    feedback_id: UUID | None = None
    message_id: UUID | None = None
    value: Value | None = None
    comment: str | None = None
    recorded_at: AwareDatetime | None = None


class Status5(StrEnum):
    pending = "pending"
    in_progress = "in_progress"
    completed = "completed"
    skipped = "skipped"


class Phase(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    order: int | None = None
    name: str | None = None
    description: str | None = None
    status: Status5 | None = None
    assigned_employee_ids: list[UUID] | None = None
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class Status6(StrEnum):
    pending = "pending"
    approved = "approved"
    rejected = "rejected"


class PhaseProposal(BaseModel):
    """
    COO AI (ジャービス) による次フェーズ提案 (E phase_proposals — GAP-022)
    """

    id: UUID | None = None
    project_id: UUID | None = None
    name: str | None = None
    description: str | None = None
    reason: str | None = None
    """
    提案理由 (「提案理由を見る」の実体)
    """
    proposed_order: int | None = None
    proposed_by: str | None = None
    status: Status6 | None = None
    approved_phase_id: UUID | None = None
    created_at: AwareDatetime | None = None
    resolved_at: AwareDatetime | None = None


class AffectedItem(BaseModel):
    id: UUID | None = None
    title: str | None = None
    lifecycle_stage: str | None = None


class ImpactAnalysis(BaseModel):
    """
    F-IMP01 影響範囲解析の結果 (dependencies 推移的走査 — GAP-022)
    """

    id: UUID | None = None
    task_id: UUID | None = None
    task_title: str | None = None
    target_phase_id: UUID | None = None
    target_phase_name: str | None = None
    affected: list[AffectedItem] | None = None
    done_count: int | None = None
    """
    影響先のうち完了済 — apply でリファクタ自動起票の対象
    """
    applied: bool | None = None


class PhaseTaskStats(BaseModel):
    """
    phase 別タスク集計 (GAP-022 — モックの phase-tasks 行の実体)
    """

    phase_id: UUID | None = None
    total: int | None = None
    done: int | None = None
    awaiting: int | None = None
    avg_score: float | None = None


class WorkflowOutput(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    phase_id: UUID | None = None
    stage: str | None = None
    html_path: str | None = None
    json_path: str | None = None
    md_path: str | None = None
    summary: str | None = None
    version: int | None = None
    delivery_phase_id: UUID | None = None
    meta: dict[str, Any] | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Sheet(BaseModel):
    name: str | None = None
    rows: list[list[str]] | None = None


class OutputSheet(BaseModel):
    """
    GAP-163 — Excel / CSV 成果物の表データ (値のみ。数式・書式は保持しない)
    """

    file_name: str | None = None
    mime: str | None = None
    editable: bool | None = None
    note: str | None = None
    sheets: list[Sheet] | None = None


class KnowledgeCandidate(BaseModel):
    """
    GAP-167 — AI が会話から拾ったナレッジ候補 (人が採用して初めてナレッジになる)
    """

    id: UUID | None = None
    workspace_id: UUID | None = None
    project_id: UUID | None = None
    title: str | None = None
    content_md: str | None = None
    category: str | None = None
    tags: list[str] | None = None
    status: Status6 | None = None
    created_at: AwareDatetime | None = None


class ShareLink(BaseModel):
    """
    GAP-162 — 成果物のクライアント共有リンク (期限つき・失効可)
    """

    id: UUID | None = None
    output_id: UUID | None = None
    label: str | None = None
    expires_at: AwareDatetime | None = None
    revoked_at: AwareDatetime | None = None
    view_count: int | None = None
    last_viewed_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    share_url: str | None = None
    """
    発行直後のみ返る (ハッシュ保存のため再取得不可)
    """


class ReferenceFile(BaseModel):
    """
    GAP-161 — スタジオに渡す参考資料 (/reference-uploads で先にアップロード済のもの)
    """

    storage_path: str
    file_name: str
    mime_type: str | None = None


class Source1(StrEnum):
    """
    workspace=この WS の版 / platform=運営既定を継承中
    """

    workspace = "workspace"
    platform = "platform"


class OutputDesignTemplate(BaseModel):
    """
    GAP-158/159 — 出力デザインテンプレ (クライアント提出 HTML/PDF の見た目の型)。版連鎖。内容の構成はスキルが担う。source=platform は運営既定を継承中。
    """

    id: UUID | None = None
    workspace_id: UUID | None = None
    """
    運営既定 (source=platform) は null
    """
    stage: str | None = None
    stage_label: str | None = None
    version: Annotated[int | None, Field(ge=1)] = None
    note: str | None = None
    source: Source1 | None = None
    """
    workspace=この WS の版 / platform=運営既定を継承中
    """
    created_at: AwareDatetime | None = None


class VersionDiff(BaseModel):
    """
    バージョン間差分 (GAP-155 — サーバ側で実 HTML 2 版から difflib 計算。モック/成果物共通)
    """

    from_id: UUID | None = None
    from_version: int | None = None
    to_id: UUID | None = None
    to_version: int | None = None
    added: int | None = None
    """
    追加行数
    """
    removed: int | None = None
    """
    削除行数
    """
    identical: bool | None = None
    """
    内容が同一 (diff 空)
    """
    diff: str | None = None
    """
    unified diff 全文
    """


class OutputAnchor(BaseModel):
    """
    成果物 HTML 内の id 付き要素 (コメント対象位置の候補 — GAP-023)
    """

    element_id: str | None = None
    label: str | None = None


class OutputFixProposal(BaseModel):
    """
    コメントへの AI (スティーブ) 修正提案 (E output_fix_proposals — GAP-023)
    """

    id: UUID | None = None
    comment_id: UUID | None = None
    output_id: UUID | None = None
    proposal: str | None = None
    status: Status6 | None = None
    applied_output_id: UUID | None = None
    created_at: AwareDatetime | None = None
    resolved_at: AwareDatetime | None = None


class Status9(StrEnum):
    decided = "decided"
    unresolved = "unresolved"


class Decision(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    phase_id: UUID | None = None
    status: Status9 | None = None
    body: str | None = None
    reflected_to: str | None = None
    resolve_note: str | None = None
    decided_by: UUID | None = None
    with_user: bool | None = None
    pinned: bool | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class DecisionCreate(BaseModel):
    project_id: UUID
    phase_id: UUID | None = None
    status: Status9 | None = "decided"
    body: Annotated[str, Field(max_length=2000, min_length=1)]
    reflected_to: Annotated[str | None, Field(max_length=500)] = None
    resolve_note: Annotated[str | None, Field(max_length=500)] = None
    decided_by: UUID | None = None
    with_user: bool | None = False


class DecisionUpdate(BaseModel):
    status: Status9 | None = None
    body: Annotated[str | None, Field(max_length=2000, min_length=1)] = None
    reflected_to: Annotated[str | None, Field(max_length=500)] = None
    resolve_note: Annotated[str | None, Field(max_length=500)] = None
    pinned: bool | None = None


class TargetType(StrEnum):
    workflow_output = "workflow_output"
    mock = "mock"
    task = "task"
    acceptance_criteria = "acceptance_criteria"


class Status12(StrEnum):
    open = "open"
    resolved = "resolved"
    deleted = "deleted"


class Comment(BaseModel):
    id: UUID | None = None
    target_type: TargetType | None = None
    target_id: UUID | None = None
    target_element_id: str | None = None
    author_user_id: UUID | None = None
    author_invitation_id: UUID | None = None
    content: str | None = None
    status: Status12 | None = None
    parent_comment_id: UUID | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class TargetAction(StrEnum):
    task_replay = "task_replay"
    knowledge_organize = "knowledge_organize"
    industry_extract = "industry_extract"
    report_summary = "report_summary"
    daily_digest = "daily_digest"
    weekly_burndown = "weekly_burndown"


class CronSchedule(BaseModel):
    """
    cron スケジュール (T-A-40)。project-scoped。Inngest 連動は別途。
    """

    id: UUID | None = None
    project_id: UUID | None = None
    name: str | None = None
    cron_expression: str | None = None
    target_action: TargetAction | None = None
    target_payload: dict[str, Any] | None = None
    enabled: bool | None = None
    next_run_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class DocType(StrEnum):
    terms_of_service = "terms_of_service"
    privacy_policy = "privacy_policy"
    tokushoho = "tokushoho"


class LegalDocument(BaseModel):
    id: UUID | None = None
    doc_type: DocType | None = None
    version: str | None = None
    locale: str | None = None
    title: str | None = None
    body_md: str | None = None
    effective_date: date | None = None
    is_current: bool | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class DataDeletionRequestResponse(BaseModel):
    request_id: UUID | None = None
    status: str | None = None
    requested_at: AwareDatetime | None = None


class ImpactAnalysisResponse(BaseModel):
    root_task_id: UUID | None = None
    affected_task_ids: list[UUID] | None = None
    affected_count: int | None = None


class PlayTaskRequest(BaseModel):
    force: bool | None = False


class PlayTaskResponse(BaseModel):
    task_id: UUID | None = None
    lifecycle_stage: str | None = None
    dispatch_status: str | None = None
    execution_id: UUID | None = None
    worktree_path: str | None = None
    bridge_command: str | None = None
    queue_position: int | None = None
    """
    並列上限超過時のキュー位置
    """


class TargetStage(StrEnum):
    triage = "triage"
    ready = "ready"
    in_progress = "in_progress"
    blocked = "blocked"
    awaiting = "awaiting"
    done = "done"


class TaskBulkLifecycleRequest(BaseModel):
    task_ids: Annotated[list[UUID], Field(max_length=200, min_length=1)]
    target_stage: TargetStage
    note: Annotated[str | None, Field(max_length=2000)] = None


class TaskBulkLifecycleResponse(BaseModel):
    requested: Annotated[int, Field(ge=0)]
    updated: Annotated[int, Field(ge=0)]
    updated_task_ids: list[UUID]
    skipped_task_ids: list[UUID]


class TaskDecisionRequest(BaseModel):
    note: Annotated[str | None, Field(max_length=2000)] = None


class DocType1(StrEnum):
    proposal = "proposal"
    estimate = "estimate"
    contract = "contract"
    nda = "nda"
    invoice = "invoice"


class SalesDocCreate(BaseModel):
    project_id: UUID
    doc_type: DocType1
    summary: Annotated[str | None, Field(max_length=4000)] = None
    html_path: Annotated[str | None, Field(max_length=500)] = None
    json_path: Annotated[str | None, Field(max_length=500)] = None
    md_path: Annotated[str | None, Field(max_length=500)] = None


class SalesDocUpdate(BaseModel):
    summary: Annotated[str | None, Field(max_length=4000)] = None
    html_path: Annotated[str | None, Field(max_length=500)] = None
    json_path: Annotated[str | None, Field(max_length=500)] = None
    md_path: Annotated[str | None, Field(max_length=500)] = None


class SalesDoc(BaseModel):
    id: UUID
    project_id: UUID
    phase_id: UUID | None = None
    doc_type: DocType1
    html_path: str | None = None
    json_path: str | None = None
    md_path: str | None = None
    summary: str | None = None
    version: Annotated[int, Field(ge=1)]
    meta: dict[str, Any] | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class SalesDocSend(BaseModel):
    """
    ドラフトのメール送信履歴 1 件 (E sales_doc_sends — GAP-018)
    """

    id: UUID | None = None
    doc_id: UUID | None = None
    to_email: str | None = None
    subject: str | None = None
    dry_run: bool | None = None
    """
    メール未設定環境での送信は true (偽装しない)
    """
    created_at: AwareDatetime | None = None


class Type3(StrEnum):
    audio = "audio"
    video = "video"
    document = "document"


class MeetingCreate(BaseModel):
    project_id: UUID
    type: Type3
    storage_path: Annotated[str, Field(max_length=500, min_length=1)]
    file_name: Annotated[str, Field(max_length=255, min_length=1)]
    file_size_bytes: Annotated[int, Field(ge=0)]
    mime_type: Annotated[str, Field(max_length=200, min_length=1)]


class Meeting(BaseModel):
    id: UUID
    project_id: UUID
    uploaded_by_user_id: UUID
    type: Type3
    storage_path: str
    file_name: str
    file_size_bytes: int
    mime_type: str
    parsed_at: AwareDatetime | None = None
    parse_result_path: str | None = None
    parse_error: str | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime


class MeetingTranscribeRequest(PlayTaskRequest):
    pass


class Status13(StrEnum):
    queued = "queued"
    already_parsed = "already_parsed"


class MeetingTranscribeResponse(BaseModel):
    id: UUID
    status: Status13
    queued_at: AwareDatetime


class MeetingUploadUrlRequest(BaseModel):
    project_id: UUID
    file_name: Annotated[str, Field(max_length=255, min_length=1)]
    mime_type: Annotated[str, Field(max_length=200, min_length=1)]


class MeetingUploadUrlResponse(BaseModel):
    upload_url: str
    storage_path: str
    bucket: str


class AccountType(StrEnum):
    workspace = "workspace"
    user = "user"
    platform = "platform"


class Scope(StrEnum):
    common = "common"
    employee_specific = "employee_specific"
    project = "project"


class SourceType(StrEnum):
    manual = "manual"
    ai_extracted = "ai_extracted"
    import_ = "import"
    mem0 = "mem0"


class KnowledgeCreate(BaseModel):
    account_id: UUID
    account_type: AccountType
    scope: Scope
    visible_in_tree: bool | None = True
    """
    false=ツリー非表示・RAG参照のみ（運営デフォルト用）
    """
    category: Annotated[str, Field(max_length=100, min_length=1)]
    title: Annotated[str, Field(max_length=200, min_length=1)]
    content_md: Annotated[str, Field(min_length=1)]
    tags: Annotated[list[str] | None, Field(max_length=50)] = None
    owner_employee_id: UUID | None = None
    parent_id: UUID | None = None
    """
    構造ツリーの親ノード。null=ルート
    """
    source_type: SourceType | None = "manual"
    source_project_id: UUID | None = None
    """
    scope=project の束縛先プロジェクト
    """
    confidence_score: Annotated[float | None, Field(ge=0.0, le=1.0)] = 0.5
    is_anonymized: bool | None = False


class KnowledgeUpdate(BaseModel):
    title: Annotated[str | None, Field(max_length=200, min_length=1)] = None
    content_md: Annotated[str | None, Field(min_length=1)] = None
    category: Annotated[str | None, Field(max_length=100, min_length=1)] = None
    tags: Annotated[list[str] | None, Field(max_length=50)] = None
    confidence_score: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    is_anonymized: bool | None = None
    parent_id: UUID | None = None
    """
    構造ツリーの親ノード（null=ルート）
    """
    visible_in_tree: bool | None = None
    """
    ナレッジツリー表示フラグ（運営デフォルトは false で非表示）
    """


class CurationRunStats(BaseModel):
    """
    GAP-153 — キュレーションバッチ 1 回分の実測
    """

    scanned: int | None = None
    proposed: int | None = None
    skipped_not_useful: int | None = None
    rejected_security: int | None = None


class Status14(StrEnum):
    pending = "pending"
    approved = "approved"
    rejected = "rejected"
    rejected_security = "rejected_security"
    skipped = "skipped"


class KnowledgeCuration(BaseModel):
    """
    GAP-153 — 運営 AI による匿名化キュレーション提案 (運営 admin 専用・テナント不可視)
    """

    id: UUID | None = None
    source_node_id: UUID | None = None
    source_account_type: str | None = None
    source_title: str | None = None
    source_workspace_name: str | None = None
    proposed_title: str | None = None
    proposed_content_md: str | None = None
    proposed_category: str | None = None
    proposed_tags: list[str] | None = None
    reason: str | None = None
    security_notes: str | None = None
    status: Status14 | None = None
    model: str | None = None
    published_node_id: UUID | None = None
    reviewed_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class AdminKnowledgeCreate(BaseModel):
    """
    運営デフォルト(platform)ナレッジ作成（T-A-50 / F-023）。account_type/account_id は server 側で固定。
    """

    category: Annotated[str, Field(max_length=100, min_length=1)]
    title: Annotated[str, Field(max_length=200, min_length=1)]
    content_md: Annotated[str, Field(min_length=1)]
    tags: Annotated[list[str] | None, Field(max_length=50)] = None
    parent_id: UUID | None = None
    visible_in_tree: bool | None = False
    """
    運営デフォルトは既定でツリー非表示（RAG 横断参照のみ）
    """
    confidence_score: Annotated[float | None, Field(ge=0.0, le=1.0)] = 0.5


class Provider1(StrEnum):
    local = "local"
    voyage = "voyage"
    none = "none"


class State(StrEnum):
    """
    ready=使える / preparing=準備中 (キーワード一致で代替) / unavailable=使えない
    """

    ready = "ready"
    preparing = "preparing"
    unavailable = "unavailable"


class EmbeddingStatus(BaseModel):
    provider: Provider1
    state: State
    """
    ready=使える / preparing=準備中 (キーワード一致で代替) / unavailable=使えない
    """
    reason: str
    """
    画面にそのまま出す 1 行説明
    """
    payer: str
    """
    誰の費用か
    """
    model_tag: str | None = None
    """
    モデル空間タグ (埋め込みと対で扱う)
    """
    next_steps: list[str]
    warnings: list[str]
    semantic_enabled: bool
    indexed: int
    """
    現行モデルで埋め込み済みの件数
    """
    total: int
    """
    対象ナレッジ総数
    """


class Knowledge(BaseModel):
    id: UUID
    account_id: UUID
    account_type: AccountType
    scope: Scope
    owner_employee_id: UUID | None = None
    parent_id: UUID | None = None
    """
    構造ツリーの親ノード。null=ルート
    """
    visible_in_tree: bool | None = None
    """
    false=ツリー非表示・RAG参照のみ（運営デフォルト用）
    """
    category: str
    title: str
    content_md: str
    tags: list[str]
    source_type: str
    source_project_id: UUID | None = None
    confidence_score: float
    usage_count: int
    is_anonymized: bool
    approved_by_user_id: UUID | None = None
    deleted_at: AwareDatetime | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class KnowledgeSearchRequest(BaseModel):
    query: Annotated[str, Field(min_length=1)]
    limit: Annotated[int | None, Field(ge=1, le=50)] = 10
    account_id: UUID | None = None
    project_id: UUID | None = None


class KnowledgeSearchHit(BaseModel):
    knowledge: Knowledge
    score: float
    """
    cosine similarity (0..1)
    """


class KnowledgeSearchResponse(BaseModel):
    query: str
    hits: list[KnowledgeSearchHit]
    total: int
    search_mode: str | None = "text_fallback"
    """
    GAP-133: 検索モードの誠実表示。semantic:voyage-3-large / semantic:local:<model> / text_fallback (意味検索が効いていない状態を UI に隠さない)
    """


class KnowledgePromoteRequest(BaseModel):
    target_workspace_id: UUID
    confidence_score: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class KnowledgePatternRequest(BaseModel):
    account_id: UUID | None = None
    category: str | None = None
    min_occurrences: Annotated[int | None, Field(ge=2, le=100)] = 2
    limit: Annotated[int | None, Field(ge=1, le=200)] = 20


class KnowledgePattern(BaseModel):
    pattern_tags: list[str]
    occurrence_count: Annotated[int, Field(ge=2)]
    representative_ids: list[UUID]
    avg_confidence: Annotated[float, Field(ge=0.0, le=1.0)]


class KnowledgePatternResponse(BaseModel):
    total: Annotated[int, Field(ge=0)]
    patterns: list[KnowledgePattern]


class KnowledgeGraphNode(BaseModel):
    """
    グラフの 1 ノード (GAP-010 — 描画用軽量フィールド)
    """

    id: UUID
    title: str
    category: str
    scope: Scope
    tags: list[str]
    usage_count: Annotated[int, Field(ge=0)]


class Kind5(StrEnum):
    parent = "parent"
    tag = "tag"


class KnowledgeGraphEdge(BaseModel):
    """
    ナレッジ間の実リンク (parent=階層 / tag=タグ共起。推測エッジなし)
    """

    source: UUID
    target: UUID
    kind: Kind5
    tag: str | None = None


class KnowledgeGraphResponse(BaseModel):
    nodes: list[KnowledgeGraphNode]
    edges: list[KnowledgeGraphEdge]
    total_nodes: Annotated[int, Field(ge=0)]
    truncated: bool
    """
    参照回数上位 120 件に切詰めたか
    """


class ReferrerType(StrEnum):
    chat_thread = "chat_thread"
    task = "task"
    decision = "decision"
    feature = "feature"


class KnowledgeReferenceItem(BaseModel):
    """
    ナレッジを参照した実体 (バックリンク 1 行 — GAP-012)
    """

    id: UUID
    referrer_type: ReferrerType
    referrer_id: UUID
    referrer_title: str
    """
    参照元の表示名 (実テーブルから解決)
    """
    context: str
    """
    参照の文脈 (例: チャット応答で参照（RAG）)
    """
    reference_count: Annotated[int, Field(ge=1)]
    last_referenced_at: AwareDatetime


class KnowledgeReferencesResponse(BaseModel):
    knowledge_id: UUID
    references: list[KnowledgeReferenceItem]
    total: Annotated[int, Field(ge=0)]


class Status15(StrEnum):
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    cancelled = "cancelled"
    timeout = "timeout"


class Execution(BaseModel):
    id: UUID
    task_id: UUID
    task_title: str
    project_id: UUID
    started_at: AwareDatetime
    completed_at: AwareDatetime | None = None
    duration_seconds: float | None = None
    status: Status15
    score: float | None = None
    ac_pass_rate: float | None = None
    test_pass_rate: float | None = None
    verification_score: float | None = None
    retry_count: int
    claude_code_session_id: str | None = None
    logs_storage_path: str | None = None
    error_summary: str | None = None
    worker_pid: int | None = None
    dispatch_status: str | None = None
    created_at: AwareDatetime


class BridgeWorkerInfo(BaseModel):
    id: str
    host_label: str
    version: str
    worker_pid: int | None = None
    last_seen_at: AwareDatetime
    connected: bool
    """
    last_seen_at が 90 秒以内
    """


class BridgePingRequest(BaseModel):
    worker_id: Annotated[str, Field(max_length=200, min_length=1)]
    host_label: Annotated[str, Field(max_length=200, min_length=1)]
    version: Annotated[str, Field(max_length=50, min_length=1)]
    worker_pid: int | None = None


class DispatchControl(BaseModel):
    paused: bool
    paused_at: AwareDatetime | None = None
    paused_by: UUID | None = None


class DispatchPromoteResponse(BaseModel):
    task_id: UUID
    title: str
    note: str


class ExecutionEvent(BaseModel):
    at: AwareDatetime
    kind: str
    """
    started / succeeded / failed / cancelled / timeout
    """
    execution_id: UUID
    task_id: UUID
    task_title: str
    score: float | None = None
    error_summary: str | None = None


class ExecLogMeta(BaseModel):
    execution_id: UUID
    task_id: UUID
    status: Status15
    started_at: AwareDatetime
    completed_at: AwareDatetime | None = None
    logs_storage_path: str | None = None
    error_summary: str | None = None
    retry_count: Annotated[int, Field(ge=0)]


class Type5(StrEnum):
    snapshot = "snapshot"
    status_change = "status_change"
    end = "end"
    error = "error"


class ExecLogEvent(BaseModel):
    type: Type5
    execution_id: UUID
    status: str | None = None
    completed_at: AwareDatetime | None = None
    error_summary: str | None = None
    logs_storage_path: str | None = None
    timestamp: AwareDatetime


class Type6(StrEnum):
    terms_of_service = "terms_of_service"
    privacy_policy = "privacy_policy"
    data_residency = "data_residency"
    ai_training_optin = "ai_training_optin"


class ConsentEntry(BaseModel):
    type: Type6
    version: Annotated[str, Field(max_length=50, min_length=1)]
    accepted: bool


class SignupRequest(BaseModel):
    email: EmailStr
    password: Annotated[str, Field(max_length=128, min_length=8)]
    display_name: Annotated[str, Field(max_length=100, min_length=1)]
    consents: Annotated[list[ConsentEntry], Field(max_length=4, min_length=2)]


class SignupResponse(BaseModel):
    user_id: UUID
    email: EmailStr
    display_name: str
    consents_recorded: Annotated[int, Field(ge=2, le=4)]
    created_at: AwareDatetime


class ToolsMode(StrEnum):
    """
    GAP-129/130: PC 操作。off=ツールなし (既定) / approve=実行ごとにユーザー承認 (Claude Code の permission prompt 同等) / auto=確認なしで自動実行 (いずれも agent_sdk モード限定・本人 opt-in)
    """

    off = "off"
    approve = "approve"
    auto = "auto"


class ChatStreamRequest(BaseModel):
    user_message: Annotated[str, Field(max_length=20000, min_length=1)]
    use_knowledge_rag: bool | None = True
    include_history: Annotated[int | None, Field(ge=0, le=50)] = 10
    rag_account_id: UUID | None = None
    attachments: Annotated[list[ChatAttachment] | None, Field(max_length=10)] = None
    """
    事前 upload-url → PUT 済の添付メタ (GAP-001 — user message に永続)
    """
    tools_mode: ToolsMode | None = "off"
    """
    GAP-129/130: PC 操作。off=ツールなし (既定) / approve=実行ごとにユーザー承認 (Claude Code の permission prompt 同等) / auto=確認なしで自動実行 (いずれも agent_sdk モード限定・本人 opt-in)
    """


class Decision1(StrEnum):
    """
    GAP-130: 承認カードへの決定。allow=実行を許可 / deny=拒否 (AI は拒否を踏まえて応答継続)
    """

    allow = "allow"
    deny = "deny"


class PcApprovalDecisionRequest(BaseModel):
    decision: Decision1
    """
    GAP-130: 承認カードへの決定。allow=実行を許可 / deny=拒否 (AI は拒否を踏まえて応答継続)
    """


class PcApprovalDecisionResponse(BaseModel):
    resolved: bool


class ChatContextPreviewRequest(BaseModel):
    user_message: Annotated[str, Field(max_length=20000, min_length=1)]
    include_history: Annotated[int | None, Field(ge=0, le=50)] = 10
    rag_account_id: UUID | None = None


class ChatContextPreviewResponse(BaseModel):
    system_prompt: str
    history_count: Annotated[int, Field(ge=0)]
    rag_hit_ids: list[UUID]


class State1(StrEnum):
    closed = "closed"
    open = "open"
    half_open = "half_open"


class CircuitBreakerState(BaseModel):
    state: State1
    failure_rate: Annotated[float, Field(ge=0.0, le=1.0)]
    total_executions: Annotated[int, Field(ge=0)]
    failed_executions: Annotated[int, Field(ge=0)]
    window_minutes: Annotated[int, Field(ge=1, le=60)]
    threshold: Annotated[float, Field(ge=0.0, le=1.0)]
    next_retry_at: AwareDatetime | None = None
    evaluated_at: AwareDatetime


class CircuitResetRequest(BaseModel):
    reason: Annotated[str, Field(max_length=2000, min_length=1)]


class PidPollRequest(BaseModel):
    heartbeat_threshold_seconds: Annotated[int | None, Field(ge=10, le=600)] = 60
    dry_run: bool | None = False


class Action(StrEnum):
    reclaimed = "reclaimed"
    dry_run_would_reclaim = "dry_run_would_reclaim"


class PidPollResult(BaseModel):
    task_id: UUID
    worker_pid: int | None = None
    last_heartbeat_at: AwareDatetime | None = None
    action: Action


class PidPollResponse(BaseModel):
    polled_at: AwareDatetime
    threshold_seconds: int
    stale_task_count: Annotated[int, Field(ge=0)]
    results: list[PidPollResult]


class Metadata(BaseModel):
    score: Annotated[float, Field(ge=0.0, le=1.0)]
    ac_pass_rate: float
    test_pass_rate: float
    verification_score: float
    files_changed: list[str] | None = None
    retry_count: int


class KanbanCompleteRequest(BaseModel):
    task_id: UUID
    summary: str
    metadata: Metadata


class Status17(StrEnum):
    pass_ = "pass"
    fail = "fail"
    skip = "skip"


class ExecutionTestResultIn(BaseModel):
    name: Annotated[str, Field(max_length=300, min_length=1)]
    file: Annotated[str | None, Field(max_length=300)] = None
    status: Status17
    duration_ms: Annotated[int | None, Field(ge=0)] = None
    detail: Annotated[str | None, Field(max_length=2000)] = None


class ExecutionTestResult(BaseModel):
    id: UUID
    execution_id: UUID
    name: str
    file: str | None = None
    status: Status17
    duration_ms: int | None = None
    detail: str | None = None
    created_at: AwareDatetime


class Kind6(StrEnum):
    mock_updated = "mock_updated"


class SpecChange(BaseModel):
    kind: Kind6
    mock_id: UUID
    screen_name: str
    current_version: int
    latest_version: int
    latest_mock_id: UUID
    detected_at: AwareDatetime


class Choice(StrEnum):
    """
    adopt=最新仕様で実装し直す / split=現状で完了 (別タスク起票) / discard=破棄して再分解待ち
    """

    adopt = "adopt"
    split = "split"
    discard = "discard"


class SpecChangeResolveRequest(BaseModel):
    choice: Choice
    """
    adopt=最新仕様で実装し直す / split=現状で完了 (別タスク起票) / discard=破棄して再分解待ち
    """
    latest_mock_id: UUID


class SpecChangeResolveResponse(BaseModel):
    choice: str
    note: str
    follow_up_task_id: UUID | None = None


class Kind7(StrEnum):
    mock = "mock"
    spec = "spec"
    acceptance_criteria = "acceptance_criteria"
    branch = "branch"
    knowledge = "knowledge"


class RelatedResource(BaseModel):
    kind: Kind7
    name: str
    meta: str
    href: str | None = None


class ChatRelayPickRequest(BaseModel):
    worker_id: Annotated[str, Field(max_length=200, min_length=1)]


class ToolsMode1(StrEnum):
    """
    GAP-134: PC 操作モード — Bridge が本人 PC で実行する
    """

    off = "off"
    approve = "approve"
    auto = "auto"


class ChatRelayPickResponse(BaseModel):
    job_id: UUID | None = None
    system_prompt: str | None = None
    prompt: str | None = None
    tools_mode: ToolsMode1 | None = None
    """
    GAP-134: PC 操作モード — Bridge が本人 PC で実行する
    """
    no_available_job: bool


class Kind8(StrEnum):
    delta = "delta"
    tool = "tool"


class ChatRelayChunksRequest(BaseModel):
    seq_start: Annotated[int, Field(ge=0)]
    texts: Annotated[list[str], Field(max_length=200, min_length=1)]
    kinds: Annotated[list[Kind8] | None, Field(max_length=200)] = None
    """
    GAP-134: texts と同長の種別 (delta=本文 / tool=実況)。省略時は全て delta
    """


class ChatRelayApprovalCreateRequest(BaseModel):
    """
    GAP-134: Bridge が CLI の許可要求を承認キューへ積む
    """

    tool: Annotated[str, Field(max_length=60, min_length=1)]
    summary: Annotated[str | None, Field(max_length=500)] = None


class ChatRelayApprovalCreateResponse(BaseModel):
    approval_id: UUID


class Decision2(StrEnum):
    pending = "pending"
    allow = "allow"
    deny = "deny"
    timeout = "timeout"


class ChatRelayApprovalStatusResponse(BaseModel):
    decision: Decision2


class BridgeTokenCreate(BaseModel):
    """
    GAP-122 — Bridge 接続トークン発行リクエスト
    """

    label: Annotated[str | None, Field(max_length=100)] = None


class BridgeTokenCreated(BaseModel):
    """
    GAP-122 — 発行応答 (raw token はこの応答で 1 度だけ)
    """

    id: UUID
    token: str
    label: str
    created_at: AwareDatetime


class BridgeTokenRow(BaseModel):
    """
    GAP-122 — トークン一覧行 (raw/hash なし)
    """

    id: UUID
    label: str
    created_at: AwareDatetime
    last_used_at: AwareDatetime | None = None
    revoked_at: AwareDatetime | None = None


class Status19(StrEnum):
    allowed = "allowed"
    allowed_warning = "allowed_warning"
    rejected = "rejected"


class ChatRelayRateLimitObservation(BaseModel):
    """
    GAP-119 — claude CLI の rate_limit_event 観測値 1 件（実値のみ転送）
    """

    status: Status19
    rate_limit_type: Annotated[str | None, Field(max_length=40)] = None
    utilization: Annotated[float | None, Field(ge=0.0, le=2.0)] = None
    resets_at: float | None = None


class ChatRelayCompleteRequest(BaseModel):
    ok: bool
    error: Annotated[str | None, Field(max_length=2000)] = None
    rate_limits: Annotated[
        list[ChatRelayRateLimitObservation] | None, Field(max_length=20)
    ] = None


class ChatRelayArtifactItem(BaseModel):
    """
    GAP-137/145 — PC 操作で生まれた成果物 1 件 (HTML は html / バイナリは content_b64 のどちらか一方。MIME はサーバが拡張子から導出)
    """

    file_name: Annotated[str, Field(max_length=200, min_length=1)]
    html: Annotated[str | None, Field(max_length=524288, min_length=1)] = None
    content_b64: Annotated[str | None, Field(max_length=11534336, min_length=1)] = None


class ChatRelayArtifactsRequest(BaseModel):
    artifacts: Annotated[
        list[ChatRelayArtifactItem], Field(max_length=10, min_length=1)
    ]


class Type7(StrEnum):
    mock = "mock"
    output = "output"
    file = "file"


class ChatRelayArtifactResult(BaseModel):
    """
    GAP-137/139/145 — 取り込み結果 (type=mock は mocks 行 / type=output は workflow_outputs 行 — 見積・提案書等 / type=file はバイナリ成果物 — 画像・PPTX・PDF・Excel・動画 等)
    """

    type: Type7
    version: int
    mock_id: UUID | None = None
    screen_name: str | None = None
    output_id: UUID | None = None
    stage: str | None = None
    title: str | None = None
    file_kind: str | None = None


class ChatConnectionWorker(BaseModel):
    """
    GAP-119 — presence 鮮度内（90 秒）の Bridge worker 1 台
    """

    host_label: str
    version: str
    last_seen_at: AwareDatetime


class ChatConnectionLastJob(BaseModel):
    """
    GAP-119 — 本人の直近 relay 実行（chat_relay_jobs、RLS で本人のみ）
    """

    status: str
    error: str | None = None
    created_at: AwareDatetime
    finished_at: AwareDatetime | None = None


class ChatConnectionPlan(BaseModel):
    """
    GAP-119 — 本人 Claude プラン枠の直近観測値（claude CLI rate_limit_event の実値のみ。 未観測の window は null — 推測で埋めない）
    """

    status: Status19
    five_hour_utilization: float | None = None
    five_hour_resets_at: AwareDatetime | None = None
    seven_day_utilization: float | None = None
    seven_day_resets_at: AwareDatetime | None = None
    observed_at: AwareDatetime


class Mode(StrEnum):
    relay = "relay"
    agent_sdk = "agent_sdk"
    api = "api"
    fake = "fake"
    unconfigured = "unconfigured"


class ChatConnectionStatusResponse(BaseModel):
    """
    GAP-119 — S-E01 接続状態パネル（実測値のみで構成）
    """

    mode: Mode
    bridge_online: bool
    workers: list[ChatConnectionWorker]
    last_job: ChatConnectionLastJob | None = None
    plan: ChatConnectionPlan | None = None


class KanbanPickRequest(BaseModel):
    worker_pid: Annotated[int, Field(ge=1)]
    project_id: UUID | None = None


class KanbanPickResponse(BaseModel):
    task_id: UUID | None = None
    execution_id: UUID | None = None
    worktree_path: str | None = None
    no_available_task: bool
    task_title: str | None = None
    task_description: str | None = None
    assigned_employee: str | None = None


class KanbanStartRequest(BaseModel):
    task_id: UUID
    execution_id: UUID
    worker_pid: Annotated[int, Field(ge=1)]
    claude_code_session_id: Annotated[str | None, Field(max_length=200)] = None


class KanbanRequestReviewRequest(BaseModel):
    task_id: UUID
    execution_id: UUID
    note: Annotated[str | None, Field(max_length=2000)] = None


class KanbanRequestChangeRequest(BaseModel):
    task_id: UUID
    execution_id: UUID
    reason: Annotated[str, Field(max_length=2000, min_length=1)]


class KanbanHeartbeatRequest(BaseModel):
    task_id: UUID
    worker_pid: Annotated[int, Field(ge=1)]


class KanbanKillRequest(BaseModel):
    task_id: UUID
    execution_id: UUID | None = None
    reason: Annotated[str, Field(max_length=2000, min_length=1)]


class Action1(StrEnum):
    picked = "picked"
    started = "started"
    completed = "completed"
    review_requested = "review_requested"
    change_requested = "change_requested"
    heartbeat_ack = "heartbeat_ack"
    killed = "killed"


class KanbanResponse(BaseModel):
    task_id: UUID
    lifecycle_stage: str
    dispatch_status: str | None = None
    execution_status: str | None = None
    action: Action1


class McpToken(BaseModel):
    id: UUID | None = None
    workspace_id: UUID | None = None
    name: str | None = None
    scopes: list[str] | None = None
    expires_at: AwareDatetime | None = None
    revoked_at: AwareDatetime | None = None
    last_used_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class McpTokenCreateResponse(McpToken):
    token: str
    """
    plaintext token (作成直後の 1 度のみ返す。以降は再表示不可)
    """


class Provider2(StrEnum):
    claude = "claude"
    openai = "openai"
    gemini = "gemini"


class ByokKey(BaseModel):
    """
    BYOK (Bring Your Own Key) API キー。plaintext / encrypted_key は応答に含めない。
    """

    id: UUID | None = None
    user_id: UUID | None = None
    provider: Provider2 | None = None
    label: str | None = None
    is_active: bool | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Type8(StrEnum):
    task_approval = "task_approval"
    phase_approval = "phase_approval"
    knowledge_write = "knowledge_write"
    comment_response = "comment_response"
    scope_change = "scope_change"


class ApprovalInboxEntry(BaseModel):
    """
    承認待ちインボックスエントリ (E-? approval_inbox)。本人のみ可視 (RLS user_id=auth.uid())。
    """

    id: UUID | None = None
    user_id: UUID | None = None
    type: Type8 | None = None
    target_type: str | None = None
    target_id: UUID | None = None
    title: str | None = None
    payload: dict[str, Any] | None = None
    status: Status6 | None = None
    resolved_at: AwareDatetime | None = None
    resolution_note: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Decision3(StrEnum):
    approve = "approve"
    reject = "reject"


class ApprovalDecideRequest(BaseModel):
    decision: Decision3
    note: Annotated[str | None, Field(max_length=2000)] = None


class ClientSigninRequest(BaseModel):
    invitation_token: Annotated[str, Field(max_length=200, min_length=10)]
    display_name: Annotated[str | None, Field(max_length=100)] = None
    agree_legal: bool | None = False
    """
    利用規約・プライバシーポリシー・越境同意 (GAP-028 — サーバー必須、false は 422)
    """
    agree_confidential: bool | None = False
    """
    機密保持同意 (GAP-028 — サーバー必須、false は 422)
    """


class ClientInvitationPreviewRequest(BaseModel):
    invitation_token: Annotated[str, Field(max_length=200, min_length=10)]


class ClientInvitationPreview(BaseModel):
    project_name: str
    workspace_name: str
    inviter_name: str | None = None
    """
    招待元 workspace オーナーの表示名 (未設定は null — 推測で埋めない)
    """
    invited_email: str
    expires_at: AwareDatetime
    remaining_days: Annotated[int, Field(ge=0)]


class ClientProjectRef(BaseModel):
    id: UUID
    name: str


class ClientSigninResponse(BaseModel):
    client_access_token: str
    """
    client_portal HS256 JWT (project_id 限定)
    """
    token_type: TokenType
    expires_at: AwareDatetime
    project: ClientProjectRef
    scopes: list[str]


class ClientProjectView(BaseModel):
    id: UUID
    name: str
    description: str | None = None
    scopes: list[str]
    viewed_as_client_display_name: str | None = None


class ClientPhaseItem(BaseModel):
    """
    クライアント向け工程 (進捗バー用の最小情報 — GAP-029)。
    """

    name: str
    order: int
    status: Status5


class ClientProjectOverview(BaseModel):
    """
    S-L03 ヘッダカード + バナーの実データ (GAP-029)。progress は実計算。
    """

    phases: list[ClientPhaseItem]
    progress_percent: Annotated[int, Field(ge=0, le=100)]
    operator_workspace_name: str | None = None
    operator_name: str | None = None
    """
    運営 workspace オーナー表示名 (未設定は null — 創作しない)
    """
    link_expires_at: AwareDatetime | None = None
    link_remaining_days: Annotated[int | None, Field(ge=0)] = None


class Format(StrEnum):
    html = "html"
    json = "json"
    md = "md"


class ClientOutputItem(BaseModel):
    """
    クライアント向け成果物 — stage 毎の最新版のみ (GAP-029)。
    """

    id: UUID
    stage: str
    stage_label: str
    version: int
    updated_at: AwareDatetime
    formats: list[Format]
    """
    実在する形式のみ (創作しない)
    """
    summary: str | None = None


class ClientMockItem(BaseModel):
    """
    クライアント向けモック — screen_name 毎の最新版 (GAP-029)。
    """

    id: UUID
    screen_name: str
    version: int
    updated_at: AwareDatetime


class ClientMocksResponse(BaseModel):
    items: list[ClientMockItem]
    total_screens: int


class TargetType1(StrEnum):
    workflow_output = "workflow_output"
    mock = "mock"


class ClientCommentCreate(BaseModel):
    """
    クライアントのコメント投稿 (comment スコープ必須 — GAP-029)。
    """

    target_type: TargetType1
    target_id: UUID
    content: Annotated[str, Field(max_length=4000, min_length=1)]


class ClientCommentItem(BaseModel):
    """
    クライアント自身のコメント + 運営からの返信 (GAP-029)。
    """

    id: UUID
    target_type: str
    target_id: UUID
    target_label: str | None = None
    content: str
    author_name: str | None = None
    is_client_author: bool
    created_at: AwareDatetime


class AuthResponse(BaseModel):
    user: User
    workspace: Workspace | None = None
    access_token: str
    refresh_token: str | None = None
    """
    opaque, httpOnly cookie
    """


class BridgeStatus(BaseModel):
    running_count: Annotated[int, Field(ge=0)]
    queued_count: Annotated[int, Field(ge=0)]
    completing_count: Annotated[int, Field(ge=0)]
    spawning_count: Annotated[int, Field(ge=0)]
    dead_count_24h: Annotated[int, Field(ge=0)]
    parallel_limit: Annotated[int, Field(ge=1)]
    available_slots: Annotated[int, Field(ge=0)]
    oldest_running_started_at: AwareDatetime | None = None
    active_worker_pids: list[int]
    evaluated_at: AwareDatetime
    paused: bool | None = False
    """
    GAP-026②: すべて一時停止中 (pick が止まる)
    """
    workers: list[BridgeWorkerInfo] | None = None
    """
    GAP-026①: 直近 5 分に ping した Bridge worker
    """


class KanbanCompleteMetadata(BaseModel):
    score: Annotated[float, Field(ge=0.0, le=1.0)]
    ac_pass_rate: Annotated[float, Field(ge=0.0, le=1.0)]
    test_pass_rate: Annotated[float, Field(ge=0.0, le=1.0)]
    verification_score: Annotated[float, Field(ge=0.0, le=1.0)]
    retry_count: Annotated[int | None, Field(ge=0, le=3)] = 0
    files_changed: Annotated[list[str] | None, Field(max_length=500)] = None
    tests: Annotated[list[ExecutionTestResultIn] | None, Field(max_length=200)] = None
    """
    GAP-025②: テストケース単位の結果 (task_execution_tests へ永続)
    """


class KanbanCompleteRequestV2(BaseModel):
    task_id: UUID
    execution_id: UUID
    summary: Annotated[str, Field(max_length=4000, min_length=1)]
    metadata: KanbanCompleteMetadata
    auto_approve: bool | None = False
