#!/usr/bin/env bash
# scan_project.sh — プロジェクトの形を抽出して計画書の冒頭に貼れる形で出力
# Usage: scan_project.sh [project_root]
# 出力: stdout に Markdown

set -euo pipefail
root="${1:-$(pwd)}"
cd "$root"

echo "# Project Scan ($root)"
echo
echo "_generated by human-grade-qa scan_project.sh_"
echo

section() { echo; echo "## $1"; echo; }

section "Repo basics"
echo '```'
[ -d .git ] && git rev-parse --abbrev-ref HEAD 2>/dev/null | sed 's/^/branch: /'
[ -f package.json ] && echo "package.json: yes"
[ -f pyproject.toml ] && echo "pyproject.toml: yes"
[ -f Cargo.toml ] && echo "Cargo.toml: yes"
[ -f go.mod ] && echo "go.mod: yes"
[ -f Gemfile ] && echo "Gemfile: yes"
[ -f composer.json ] && echo "composer.json: yes"
[ -f vercel.json ] || [ -f vercel.ts ] && echo "vercel config: yes"
echo '```'

section "Dev scripts (package.json)"
if [ -f package.json ]; then
  echo '```json'
  node -e "try{const p=require('./package.json');console.log(JSON.stringify(p.scripts||{},null,2))}catch(e){console.log('{}')}" 2>/dev/null || cat package.json | grep -A 30 '"scripts"' | head -40
  echo '```'
else
  echo "_no package.json_"
fi

section "Detected frameworks"
echo '```'
grep -E '"(next|react|vue|nuxt|svelte|astro|vite|express|fastify|hono|nestjs)"' package.json 2>/dev/null | sed 's/^ *//' | head -20 || true
[ -f pyproject.toml ] && grep -E '(fastapi|django|flask|starlette|uvicorn)' pyproject.toml | head -10 || true
echo '```'

section "Routes (frontend)"
echo '```'
{
  find src/pages app pages -maxdepth 4 -type f \( -name '*.tsx' -o -name '*.ts' -o -name '*.vue' -o -name '*.svelte' \) 2>/dev/null
  find src/router src/routes -maxdepth 3 -type f 2>/dev/null
} | head -60
echo '```'

section "APIs (backend)"
echo '```'
{
  grep -rE '@(app|router)\.(get|post|put|delete|patch)\(' --include='*.py' . 2>/dev/null | head -40
  grep -rE 'app\.(get|post|put|delete|patch)\(' --include='*.js' --include='*.ts' . 2>/dev/null | head -40
  grep -rE 'router\.(get|post|put|delete|patch)\(' --include='*.js' --include='*.ts' . 2>/dev/null | head -40
} 2>/dev/null | head -80
echo '```'

section "Auth implementation hints"
echo '```'
grep -rliE '(auth(Middleware)?|passport|next-auth|clerk|supabase.*auth|jwt|bearer)' --include='*.ts' --include='*.tsx' --include='*.js' --include='*.py' src functions server backend 2>/dev/null | head -30 || true
echo '```'

section "DB schema / migrations"
echo '```'
find migrations db/migrate prisma supabase/migrations -type f 2>/dev/null | head -40
[ -f prisma/schema.prisma ] && echo "prisma: prisma/schema.prisma"
echo '```'

section "Environment variable keys (from .env.example only)"
echo '```'
for f in .env.example .env.local.example .env.sample functions/.env.example; do
  [ -f "$f" ] && { echo "--- $f"; grep -E '^[A-Z_][A-Z0-9_]*=' "$f" | sed 's/=.*$/=***/' | head -40; }
done
echo '```'

section "Existing tests"
echo '```'
{
  find tests __tests__ test e2e cypress playwright -type f \( -name '*.spec.*' -o -name '*.test.*' \) 2>/dev/null | head -60
  [ -f playwright.config.ts ] && echo "playwright.config.ts: yes"
  [ -f cypress.config.ts ] && echo "cypress.config.ts: yes"
} 2>/dev/null
echo '```'

section "Past QA runs"
if [ -d .qa/runs ]; then
  echo '```'
  ls -1 .qa/runs | tail -10
  echo '```'
else
  echo "_no .qa/runs/ yet_"
fi
